### ISSUE TITLE
I cannot insert in  Mysql

### ISSUE THREAD

**Issue by anorna** [UnaBiz/sigfox-gcloud-data#1]
i am at this point:
it recognices the first 4 fields but the body is not well formated as a field, so the insert fails

insert into `sigfox` (`callbackTimestamp`, `datetime`, `localdatetime`, `uuid`, `{ "device" : "1D25D8", "data" : "0000b441", "time" : "1541235631", "duplicate": "false", "snr": "16`.`71", "station": "0AFC", "avgSnr": "23`.`80", "lat": "39`.`0", "lng": "0`.`0", "rssi": "-123`.`00", "seqNumber": "1714", "ack": "true", "longPolling": "false" }`) values (1541235632863, '2018-11-03 09:00:32', '2018-11-03 17:00:32', 'a44aacb1-fe91-404b-bdc0-9d1567ca93bf', '') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`0", "lng": "0`.`0", "rssi": "-123`.`00", ' at line 1 Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`0", "lng": "0`.`0", "rssi": "-123`.`00", ' at line 1 at Query.Sequence._packetToError (/user_code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14) at Query.ErrorPacket (/user_code/node_modules/mysql/lib/protocol/sequences/Query.js:77:18) at Protocol._parsePacket (/user_code/node_modules/mysql/lib/protocol/Protocol.js:278:23) at Parser.write (/user_code/node_modules/mysql/lib/protocol/Parser.js:76:12) at Protocol.write (/user_code/node_modules/mysql/lib/protocol/Protocol.js:38:16) at Socket.<anonymous> (/user_code/node_modules/mysql/lib/Connection.js:91:28) at Socket.

**Comment by anorna** [comment]
solved

   const body1 =  Object.keys(body0)[4];
    const body2 = JSON.parse(body1);
    const body = Object.assign({}, body0 , body2);
